### ISSUE TITLE
Requeting pretrained model.

### ISSUE THREAD

**Issue by sushantakpani** [BUTSpeechFIT/speakerbeam#2]
I want to extract target speech from a multi speaker audio file using voice clue of the target speaker. Please let me know if there is any API or pre-trained model available to address my need.

**Comment by zmolikova** [comment]
Hi,
A model pre-trained on Libri2Mix can be found in `example/model.pth`. To see how to apply the model, you can look at `egs/libri2mix/eval.py` and modify it to load your data.
We unfortunately don't have a more simple API ready; the repository is meant more as a support for further research. I will be happy to help more if you face any issues.

**Comment by sushantakpani** [comment]
Hi @zmolikova 

Thank you for your time and reply. 
I will check the existing pre-trained model. 
Can you suggest any other dataset or data augmentation method to build better model for a target speaker speech extraction?

**Comment by zmolikova** [comment]
For datasets, you can check our recent [overview paper](https://arxiv.org/abs/2301.13341); in Table 3, we summarize the commonly used ones.
Other ways to augment data that are sometimes used are dynamic mixing (that is, creating mixtures of the available single speaker utterances on-the-fly during training rather than using the limited pre-defined set of training mixtures) or speed perturbation (slowing down or speeding up the sources by ~5% before mixing). For these, you could take inspiration from a [recipe in Asteroid](https://github.com/asteroid-team/asteroid/tree/bd3caa3963cf2f8756da17801958073001aaa0f2/egs/wham/DynamicMixing) that employs both of these on the WHAM dataset (for speech separation, however, not target speech extraction).

**Comment by zmolikova** [comment]
Closing the issue for now, feel free to re-open or submit a new one if you have more questions.
